use_frameworks!

platform :ios, '10.0'

target 'testClass_Example' do
  pod 'testClass', :path => '../'

  target 'testClass_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
